// Code generated by Kitex v0.15.2. DO NOT EDIT.

package combine

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	v1 "kitexidltest/kitex_gen/base/packagea/v1"
	v1 "kitexidltest/kitex_gen/example/v1"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Example": kitex.NewMethodInfo(
		exampleHandler,
		newExampleArgs,
		newExampleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"ExampleA": kitex.NewMethodInfo(
		exampleAHandler,
		newExampleAArgs,
		newExampleAResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	combineServiceInfo                = NewServiceInfo()
	combineServiceInfoForClient       = NewServiceInfoForClient()
	combineServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return combineServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return combineServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return combineServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Combine"
	handlerType := (*v1.Combine)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "idl.protobuffer.example.v1",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func exampleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ExampleRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.Combine).Example(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ExampleArgs:
		success, err := handler.(v1.Combine).Example(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ExampleResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newExampleArgs() interface{} {
	return &ExampleArgs{}
}

func newExampleResult() interface{} {
	return &ExampleResult{}
}

type ExampleArgs struct {
	Req *v1.ExampleRequest
}

func (p *ExampleArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ExampleArgs) Unmarshal(in []byte) error {
	msg := new(v1.ExampleRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ExampleArgs_Req_DEFAULT *v1.ExampleRequest

func (p *ExampleArgs) GetReq() *v1.ExampleRequest {
	if !p.IsSetReq() {
		return ExampleArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ExampleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ExampleArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ExampleResult struct {
	Success *v1.ExampleResponse
}

var ExampleResult_Success_DEFAULT *v1.ExampleResponse

func (p *ExampleResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ExampleResult) Unmarshal(in []byte) error {
	msg := new(v1.ExampleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ExampleResult) GetSuccess() *v1.ExampleResponse {
	if !p.IsSetSuccess() {
		return ExampleResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ExampleResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ExampleResponse)
}

func (p *ExampleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ExampleResult) GetResult() interface{} {
	return p.Success
}

func exampleAHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(v1.ExampleA)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(v1.Combine).ExampleA(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ExampleAArgs:
		success, err := handler.(v1.Combine).ExampleA(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ExampleAResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newExampleAArgs() interface{} {
	return &ExampleAArgs{}
}

func newExampleAResult() interface{} {
	return &ExampleAResult{}
}

type ExampleAArgs struct {
	Req *v1.ExampleA
}

func (p *ExampleAArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ExampleAArgs) Unmarshal(in []byte) error {
	msg := new(v1.ExampleA)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ExampleAArgs_Req_DEFAULT *v1.ExampleA

func (p *ExampleAArgs) GetReq() *v1.ExampleA {
	if !p.IsSetReq() {
		return ExampleAArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ExampleAArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ExampleAArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ExampleAResult struct {
	Success *v1.ExampleResponse
}

var ExampleAResult_Success_DEFAULT *v1.ExampleResponse

func (p *ExampleAResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ExampleAResult) Unmarshal(in []byte) error {
	msg := new(v1.ExampleResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ExampleAResult) GetSuccess() *v1.ExampleResponse {
	if !p.IsSetSuccess() {
		return ExampleAResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ExampleAResult) SetSuccess(x interface{}) {
	p.Success = x.(*v1.ExampleResponse)
}

func (p *ExampleAResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ExampleAResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Example(ctx context.Context, Req *v1.ExampleRequest) (r *v1.ExampleResponse, err error) {
	var _args ExampleArgs
	_args.Req = Req
	var _result ExampleResult
	if err = p.c.Call(ctx, "Example", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ExampleA(ctx context.Context, Req *v1.ExampleA) (r *v1.ExampleResponse, err error) {
	var _args ExampleAArgs
	_args.Req = Req
	var _result ExampleAResult
	if err = p.c.Call(ctx, "ExampleA", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
