// Code generated by Kitex v0.15.2. DO NOT EDIT.

package v1

import "github.com/cloudwego/prutal"

type ExampleA struct {
}

func (x *ExampleA) Reset() { *x = ExampleA{} }

func (x *ExampleA) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ExampleA) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }
