// Code generated by Kitex v0.15.2. DO NOT EDIT.

package v1

import (
	"context"
	"kitexidltest/kitex_gen/base/packagea/v1"
	"kitexidltest/kitex_gen/base/packageb/v1"

	"github.com/cloudwego/prutal"
)

type ExampleRequest struct {
	ExampleA *v1.ExampleA `protobuf:"bytes,1,opt,name=example_a" json:"example_a,omitempty"`
	ExampleB *v1.ExampleB `protobuf:"bytes,2,opt,name=example_b" json:"example_b,omitempty"`
}

func (x *ExampleRequest) Reset() { *x = ExampleRequest{} }

func (x *ExampleRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ExampleRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ExampleRequest) GetExampleA() *v1.ExampleA {
	if x != nil {
		return x.ExampleA
	}
	return nil
}

func (x *ExampleRequest) GetExampleB() *v1.ExampleB {
	if x != nil {
		return x.ExampleB
	}
	return nil
}

type ExampleResponse struct {
	ExampleA *v1.ExampleA `protobuf:"bytes,1,opt,name=example_a" json:"example_a,omitempty"`
	ExampleB *v1.ExampleB `protobuf:"bytes,2,opt,name=example_b" json:"example_b,omitempty"`
}

func (x *ExampleResponse) Reset() { *x = ExampleResponse{} }

func (x *ExampleResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ExampleResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *ExampleResponse) GetExampleA() *v1.ExampleA {
	if x != nil {
		return x.ExampleA
	}
	return nil
}

func (x *ExampleResponse) GetExampleB() *v1.ExampleB {
	if x != nil {
		return x.ExampleB
	}
	return nil
}

type Combine interface {
	Example(ctx context.Context, req *ExampleRequest) (res *ExampleResponse, err error)
	ExampleA(ctx context.Context, req *v1.ExampleA) (res *ExampleResponse, err error)
}
