// Code generated by Kitex v0.15.2. DO NOT EDIT.

package v1

import "github.com/cloudwego/prutal"

type ExampleB struct {
}

func (x *ExampleB) Reset() { *x = ExampleB{} }

func (x *ExampleB) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *ExampleB) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }
